# Generated by Django 5.2.15 on 2026-06-19 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="专注会话", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "进行中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "speed_rate",
                    models.FloatField(
                        default=10.0, help_text="虚拟时间倍速系数，如 10 表示 1:10"
                    ),
                ),
                (
                    "start_real_timestamp",
                    models.FloatField(help_text="任务开始时的真实 Unix 时间戳"),
                ),
                (
                    "last_pause_real_timestamp",
                    models.FloatField(
                        blank=True, help_text="上次暂停时的真实时间戳", null=True
                    ),
                ),
                (
                    "accumulated_virtual_seconds",
                    models.FloatField(
                        default=0.0, help_text="已累积的虚拟秒数（暂停前累计）"
                    ),
                ),
                (
                    "total_planned_virtual_seconds",
                    models.FloatField(
                        default=3600.0, help_text="计划的虚拟总时长（秒）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="focus_focus_user_id_1228f9_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="focus_focus_user_id_4571a4_idx",
                    ),
                    models.Index(
                        fields=["start_real_timestamp"],
                        name="focus_focus_start_r_37525c_idx",
                    ),
                ],
            },
        ),
    ]
